### ISSUE TITLE
requestReview shown each start

### ISSUE THREAD

**Issue by brightsider** [arashpayan/appirater#263]
I think when [SKStoreReviewController requestReview] called, appirater should mark it like user press "Later" or " No, Thanks"

**Comment by konDeichmann** [comment]
Did you call it in development mode?

> Note
When you call this method while your app is still in development mode, a rating/review request view is always displayed so that you can test the user interface and experience. However, this method has no effect when you call it in an app that you distribute using TestFlight.

see: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

**Comment by arashpayan** [comment]
Since the last release, [2.3.0 ](https://github.com/arashpayan/appirater/releases/tag/2.3.0), Appirater records a call to `[SKStoreReviewController requestReview]` as the current version being rated. As @konDeichmann suggested, make sure you're not running in development mode and that you're not calling `[Appirater setDebug:YES]`.
